# Generated by Django 4.2.13 on 2026-03-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Motorcycle', 'Motorcycle'), ('Vehicle', 'Unknown Vehicle')], default='Vehicle', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='UNKNOWN', max_length=30)),
                ('speed', models.FloatField()),
                ('speed_limit', models.IntegerField(default=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violations/%Y/%m/%d/')),
                ('video_source', models.CharField(default='traffic.mp4', max_length=255)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
